name: Backend Tests

on:
  push:
    paths:
      - "hdt-qs-backend/**"

defaults:
  run:
    working-directory: hdt-qs-backend

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [11, 17]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Load setting
        run: ./ci_login.sh
      - name: Run tests
        run: mvn test -s settings.xml
