name: Pull request Tests Backend

on:
  pull_request:
    paths:
      - "hdt-qs-backend/**"

defaults:
  run:
    working-directory: hdt-qs-backend

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [11, 17]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-jdk${{ matrix.jdk }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-jdk${{ matrix.jdk }}-maven-
      - name: Create login
        run: ./ci_login.sh
      - name: Validate format
        run: mvn -B formatter:validate -s settings.xml
      - name: Compiling
        run: mvn -B -U clean install -Dmaven.javadoc.skip=true -DskipTests -s settings.xml
      - name: Test
        run: mvn -B clean test -Dmaven.javadoc.skip=true -s settings.xml
